
################

#todo: warning
disabled_rules:
  - todo
  
################



opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - direct_return
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - implicit_getter
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - local_doc_comment
  - lower_acl_than_parent
  - mark
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - no_space_in_method_call
  - non_overridable_class_declaration
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_swiftui_state
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_void_return
  - reduce_boolean
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - test_case_accessibility
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_synthesized_initializer
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition

  - toggle_bool
  - modifier_order
  #- file_name



custom_rules:
  russian_text:
    name: "Russian text"
    regex: "^[^\n]*[а-яА-ЯёЁ]+[^\n]*$"
    match_kinds:
      - comment
      - doccomment
    message: "Contain russian"
    severity: warning

  structured_todo:
    name: "Structured TODO"
    regex: '\/\/\s*(TODO|FIXME)(?!: \[[A-Z]{2,}\])'
    message: "TODO/FIXME should be annotated like `// TODO: [REF] explain what and why`"
    severity: warning

  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
  
#  no_force_unwrap:
#    name: "No Force Unwrap"
#    regex: '[a-zA-Z0-9_]+\!'
#    message: "Avoid using force unwraps (!), use optional binding instead."
#    severity: error

#  test_naming:
#    name: "Test Naming Convention"
#    regex: 'func\s+(?!test[A-Z])\w+\s*\(\)'
#    message: "Test methods should start with 'test' in CamelCase (e.g., testButtonTap)"
#    included: '.*Tests\.swift'
#    severity: warning
